### ISSUE TITLE
Missing DATA element

### ISSUE THREAD

**Issue by rshawkins** [liberu-genealogy/php-gedcom#2]
If a record has a DATA sub record like the following

1 BURI
2 PLAC Warwick, Lambton County, Ontario, CANADA
2 SOUR @S0002@
3 DATA
4 TEXT James Hawkins
5 CONT died May 16 1894
5 CONT aged 82 yrs

The DATA sub record doesn't seem to be parsed or there doesn't seem to be a way to retrieve it.

<details open>
<summary>Checklist</summary>

- [X] Modify `src/Record/Data.php` ! No changes made  [Edit](https://github.com/liberu-genealogy/php-gedcom/edit/sweep/missing_data_element/src/Record/Data.php)
- [X] Running GitHub Actions for `src/Record/Data.php` ✗  [Edit](https://github.com/liberu-genealogy/php-gedcom/edit/sweep/missing_data_element/src/Record/Data.php)
- [X] Modify `src/Parser.php` ✓ https://github.com/liberu-genealogy/php-gedcom/commit/479e5dcc49b31dfe4750b91c96fb957ee613a608 [Edit](https://github.com/liberu-genealogy/php-gedcom/edit/sweep/missing_data_element/src/Parser.php#L96-L139)
- [X] Running GitHub Actions for `src/Parser.php` ✓  [Edit](https://github.com/liberu-genealogy/php-gedcom/edit/sweep/missing_data_element/src/Parser.php#L96-L139)
</details>

**Comment by curtisdelicata** [comment]
Please send a pull request. Thank you.
