### ISSUE TITLE
Your Example does not work

### ISSUE THREAD

**Issue by cmette** [liberu-genealogy/php-gedcom#3]
Hello team,
your example does not work
```
$parser = new \Gedcom\Parser();
$gedcom = $parser->parse('tmp.ged');

foreach ($gedcom->getIndi() as $individual) {
    echo $individual->getId() . ': ' . current($individual->getName())->getSurn() .
        ', ' . current($indi->$individual())->getGivn();
}
```
this is not a valid php code. Can you give a working example?

These lines are not executable in any PHP version:
```
echo $individual->getId() . ': ' . current($individual->getName())->getSurn() .
        ', ' . current($indi->$individual())->getGivn();
```
In my case the parser seems to work, but I can't access the decoded objects like name etc.

This part
```
current($individual->getName())->getSurn()
```
throws an exception
```
Call to a member function getSurn() on bool
```
Calling current in foreach should not make sense!

and this part
```
current($indi->$individual())->getGivn()
```
is not defined, because $indi is not defined and $indi->$individual() makes no sense.

Can you help with a few tips or provide a more detailed example?

Best regards
cmette

<details open>
<summary>Checklist</summary>

- [X] Modify `README.md` ✓ https://github.com/liberu-genealogy/php-gedcom/commit/8b60952e12708d5016e6bd75e6eb5e4c6a3ebefe [Edit](https://github.com/liberu-genealogy/php-gedcom/edit/sweep/your_example_does_not_work/README.md#L53-L62)
- [X] Running GitHub Actions for `README.md` ✓  [Edit](https://github.com/liberu-genealogy/php-gedcom/edit/sweep/your_example_does_not_work/README.md#L53-L62)
</details>

**Comment by cmette** [comment]
Try this
```
/* @var Indi $individual */
foreach ($gedcom->getIndi() as $individual) {
  /* @var Name $name */
  foreach ($individual->getName() as $name) {
    echo "id:{$individual->getId()} name:{$name->getName()} surn: {$name->getSurn()}";
  }
}
```
and fix this in Gedcom\Record\ObjeRef\File\Form;
```
// add the _ before form like
protected $_form;
// add the _ before titl like
protected $_titl;
// add this line!
protected $_date;
```

**Comment by curtisdelicata** [comment]
Please send a pull request. Thank you.
