### ISSUE TITLE
PSR-4 Error during composer install

### ISSUE THREAD

**Issue by MGeurts** [liberu-genealogy/php-gedcom#49]
Class Gedcom\Record\Indi located in ./vendor/liberu-genealogy/php-gedcom/src/Gedcom/Record/Indi.php does not comply with psr-4 autoloading standard. Skipping.

**Comment by curtisdelicata** [comment]
Thank you for the recent issues. Bit busy at moment so may be a delay in fixes. Any pull requests are welcome and will most likely be merged in after review.

**Comment by MGeurts** [comment]
It seems to me, this is a reappearance of https://github.com/liberu-genealogy/php-gedcom/issues/45
