### ISSUE TITLE
Bug: Warning: Undefined array key 2 in Fam.php

### ISSUE THREAD

**Issue by stuntdawg** [liberu-genealogy/php-gedcom#62]

**Comment by stuntdawg** [comment]
All I did was load the .ged file and immediately get this:

Warning: Undefined array key 2 in /../vendor/liberu-genealogy/php-gedcom/src/Parser/Fam.php on line: 93

the specific lines are:

                case 'NCHI':
                    $fam->setNchi(trim((string) $record[2]));
                    break;

and I could resolve the issue with this:

                case 'NCHI':
                    if(isset($record[2])) $fam->setNchi(trim((string) $record[2]));
                    break;

**Comment by curtisdelicata** [comment]
Merged.
